version: "3.4"
services:
  auth-srv:
    command: node src/server.js
    build:
      context: ./auth-srv
      dockerfile: Dockerfile
    ports:
      - published: ${AUTH_SRV_PORT:-3000}
        target: 3000
    volumes:
      - ./auth-srv/:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
  movies-srv:
    command: node src/server.js
    build:
      context: ./movies-srv
      target: debug
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./movies-srv/:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}

