version: "2.4"
services:
  auth-srv:
    container_name: ${AUTH_SRV_NAME:-auth-srv}
    command: node src/server.js
    build:
      context: ./auth-srv
      dockerfile: Dockerfile
    ports:
      - published: ${AUTH_SRV_PORT:-3000}
        target: 3000
    volumes:
      - ./auth-srv/:/app/
    environment:
      AUTH_SRV_PORT: ${AUTH_SRV_PORT}
      JWT_SECRET: ${JWT_SECRET}
  movies-srv:
    container_name: ${MOVIES_SRV_NAME:-movies-srv}
    command: node src/server.js
    build:
      context: ./movies-srv
      dockerfile: Dockerfile
    ports:
      - ${MOVIES_SRV_PORT}:8080
      - 9229:9229
      - 9230:9230
    depends_on:
      - auth-srv
      - mongodb
    volumes:
      - ./movies-srv/:/app/
    environment:
      AUTH_SRV_PORT: ${AUTH_SRV_PORT}
      MOVIES_SRV_PORT: ${MOVIES_SRV_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      DB_HOST: ${MONGODB_SRV_NAME:-mongodb}
      DB_PORT: ${DB_PORT:-27017}
  mongodb:
    container_name: ${MONGODB_SRV_NAME:-mongodb}
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
