name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build
      - name: Run the stack
        run: docker-compose up -d
      - name: Run the tests on movies-srv
        run: docker-compose run --rm --entrypoint "" movies-srv npm test
