name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build & run the stack
        run: JWT_SECRET=$JWT_SECRET MONGODB_USERNAME=$MONGODB_USERNAME MONGODB_PASSWORD=$MONGODB_PASSWORD OMDB_APIKEY=$OMDB_APIKEY docker-compose up --build -d
        env:
          AUTH_SRV_PORT: 3000
          MOVIES_SRV_PORT: 3002
          EXAMPLE_DB_NAME: "example-database"

      - name: Run the tests on movies-srv
        run: docker-compose run --rm --entrypoint "" movies-srv npm test
